### ISSUE TITLE
Any recommendation if it does not show in the 

### ISSUE THREAD

**Issue by ceased-ebc** [WeProgramIT/cryptowoo-bitcoin-cash-addon#2]
Dropdown in the front end?

**Comment by Olsm** [comment]
I am not sure what you mean?
Do you mean this addon license menu?
That is only in the hd wallet addon and dash addon.
There is no license in this plugin.

After you activate the plugin:
1. Enter Extended Public Key in Wallet Settings -> HD Wallet
2. Chose processing api in Payment Processing -> Block Chain Access
3. Chose exchange in Pricing -> Preferred Exchanges
