### ISSUE TITLE
Error activating the plugin.

### ISSUE THREAD

**Issue by andres-pinilla** [WeProgramIT/cryptowoo-bitcoin-cash-addon#6]
Hi, when trying to activate the plugin, the following error appears:

Fatal error: Class 'CW_License_Menu' not found in /var/.../wp-content/plugins/cryptowoo-bitcoin-cash-addon/cryptowoo-bitcoin-cash-addon.php on line 33.

Thanks,

Andres

**Comment by Olsm** [comment]
You downloaded the master branch. The next release is not available for production yet. It requires some changes in the HD wallet addon which is coming soon. 

Download the latest release for production here:

https://github.com/Olsm/cryptowoo-bitcoin-cash-addon/releases/latest

**Comment by andres-pinilla** [comment]
Thanks, I had downloaded the version available on cryptowoo.com. I downloaded the version you indicated and it worked.
