### ISSUE TITLE
Please change the Bitcoin Cash logo at checkout

### ISSUE THREAD

**Issue by andres-pinilla** [WeProgramIT/cryptowoo-bitcoin-cash-addon#7]
Please change the Bitcoin Cash logo for the green logo.

**Comment by andres-pinilla** [comment]
`        }

        i.cc.BCH, i.cc.BCH-alt {
            color: #70c659;
        }`

**Comment by Olsm** [comment]
It is discussable if the bitcoin cash logo should be green or not. I think that it should be the official logo, and the official logo is the same but slightly tilted. What do you think about slightly tilting the logo instead?

**Comment by andres-pinilla** [comment]
I think the green color is better, it avoids confusion and it looks better.

Image: https://imgur.com/a/V6vo5

**Comment by Olsm** [comment]
This has nothing to do with confusion. The currency have to be chosen in the drop down by the customer before proceeding in text. You cannot confuse the dropdown elements "Bitcoin" and "Bitcoin Cash". This is just the currency symbol next to prices.

I also would like to remind you that this plugin is made for Bitcoin Cash, not Bcash.

**Comment by Olsm** [comment]
After discussion with the bitcoin community and more research, I see that there is big interest to change the logo to green. So this will be done in the next version. Thank you for your suggestion!

**Comment by andres-pinilla** [comment]
Thanks a lot!.

**Comment by Olsm** [comment]
Change implemented in version 1.3
