### ISSUE TITLE
Add Cash Address Support

### ISSUE THREAD

**Issue by Olsm** [WeProgramIT/cryptowoo-bitcoin-cash-addon#8]
https://www.bitcoinabc.org/cashaddr

**Comment by andres-pinilla** [comment]
+1. Thanks.

**Comment by rnzdev** [comment]
Hi @Olsm,

We'd like to know the release date of the updates.

Thank you,
Rnz

**Comment by andres-pinilla** [comment]
Hi, @Olsm,

Do you have any info of the updates?.

Thanks,

Andres

**Comment by renzramos** [comment]
Any release? :)

**Comment by maemon** [comment]
Hey @Olsm if you want, we can provide you a bounty for adding this feature. We really need it!

**Comment by Olsm** [comment]
@andres-pinilla @rnzdev @renzramos @maemon
This was added in version 1.4 released March 23, 2019.
https://github.com/WeProgramIT/cryptowoo-bitcoin-cash-addon/releases/tag/v1.4

**Comment by Olsm** [comment]
@maemon Thank you for your offer of a bounty to add this however cash address support was already released on March 23, before you posted this comment.

We would very much appreciate any donation which will go towards more development of this plugin. You can find donation info in the readme. Thank you. :)
