### ISSUE TITLE
0-conf support

### ISSUE THREAD

**Issue by mikolav** [WeProgramIT/cryptowoo-bitcoin-cash-addon#9]
I'm unable to set the required confirmations below 1 in Cryptowoo, are 0-conf payments not supported? IMO the focus on 0-conf in Bitcoin Cash development is a big feature of BCH.

**Comment by Ganacontrol** [comment]
Please allow 0 conf for BCH or I will be forced to switch solutions.

Bitpay allows 0-conf, Microsoft uses 0conf through bitpay. 
It has been proven it is at least highly secure for tx up to $60,000 USD.

PLEASE PLEASE PLEASE FIX ASAP. I have 20+ clients who'll be integrating crypto payments and I will give you as many license purchases if you fix this within 30 days.
